name = "options-tracker-worker"
main = "worker/src/index.js"
compatibility_date = "2024-01-01"

[build]
command = "cd frontend && npm run build"

[[pages_build_output_dir]]
directory = "frontend/dist"
